### ISSUE TITLE
how to set language into token

### ISSUE THREAD

**Issue by ibilous** [xm-online/xm-commons#81]
Hello guys. 

When server throws an error it could be translated into several language. Language can be set as request parameter aka <domain>/language=en, or it could be retrieved [from token](https://github.com/xm-online/xm-commons/blob/cdaa5a38bd32dbd87c604406c233822b6be60e9f/xm-commons-i18n/src/main/java/com/icthh/xm/commons/i18n/spring/service/LocalizationMessageService.java#L68). 
Our client developer prefers not to use request parameter. But i cannot get how a language can be set into that token. Could u help me pls ?

**Comment by major13ua** [comment]
language is part of **a user profile** and already present in **profile** information.
